name: CI Pipeline for Postman tests

on:
  push:
    branches:
      - yaml

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Setup Firebase Config
        run: |
          echo "import { initializeApp } from 'firebase/app';" > src/firebaseConfig.js
          echo "import { getFirestore } from 'firebase/firestore';" >> src/firebaseConfig.js
          echo "const firebaseConfig = {" >> src/firebaseConfig.js
          echo "  apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> src/firebaseConfig.js
          echo "  authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> src/firebaseConfig.js
          echo "  projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> src/firebaseConfig.js
          echo "  storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> src/firebaseConfig.js
          echo "  messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> src/firebaseConfig.js
          echo "  appId: '${{ secrets.FIREBASE_APP_ID }}'," >> src/firebaseConfig.js
          echo "  measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'" >> src/firebaseConfig.js
          echo "};" >> src/firebaseConfig.js
          echo "const app = initializeApp(firebaseConfig);" >> src/firebaseConfig.js
          echo "const db = getFirestore(app);" >> src/firebaseConfig.js
          echo "export { db };" >> src/firebaseConfig.js

      - name: Setup Service Account Key
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > serviceAccountKey.json

      - name: Start Server
        run: |
          nohup npm start &

      - name: Wait for Server to be Up
        run: sleep 10

      - name: Run Postman Tests
        run: |
          npm run build
          newman run postman/todo-api.postman_collection.json -e postman/todo-api.postman_environment.json

    env:
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
      FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
      FIREBASE_CLIENT_X509_CERT_URL: ${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}
